export const MessageType = {
    FONT_LIST_LOADED: 'FONT_LIST_LOADED',
    ADD_OR_REMOVE_MARKED_FONT: 'ADD_OR_REMOVE_MARKED_FONT',
    FONT_CLICK: 'FONT_CLICK',
    FONT_CHANGED: 'FONT_CHANGED',
    SELECTION_CHANGE: 'SELECTION_CHANGE',
};

export type LanguageType = 'EN' | 'CN';
