export const MessageType = {
    FONT_LIST_LOADED: 'FONT_LIST_LOADED',
    ADD_OR_REMOVE_MARKED_FONT: 'ADD_OR_REMOVE_MARKED_FONT',
    FONT_CLICK: 'FONT_CLICK',
    FONT_CHANGED: 'FONT_CHANGED',
    SELECTION_CHANGE: 'SELECTION_CHANGE',
};

export type LanguageType = 'EN' | 'CN';

// List of serif typefaces 衬线字体
const serif = [
    'Adobe Jenson',
    'Albertus',
    'Aldus',
    'Alexandria',
    'American Typewriter',
    'Amiri',
    'Archer',
    'Arno',
    'Aster',
    'Athelas',
    'Baskerville',
    'Bauer Bodoni',
    'Bell',
    'Bembo',
    'Benguiat',
    'Bernhard Modern',
    'Bodoni',
    'Bookman',
    'Bookerly',
    'Bulmer',
    'Caledonia',
    'Calisto',
    'Cambria',
    'Caslon',
    'Centaur',
    'Century Schoolbook',
    'Chaparral',
    'Bitstream Charter',
    'Cheltenham',
    'City',
    'Clarendon',
    'Cochin',
    'Computer Modern',
    'Constantia',
    'Constructium',
    'Copperplate Gothic',
    'DejaVu Serif',
    'Didot',
    'Droid Serif',
    'Emerson',
    'FF Scala',
    'Footlight',
    'Friz Quadrata',
    'ITC Galliard',
    'Garamond',
    'Gentium',
    'Georgia',
    'Goudy Old Style',
    'Granjon',
    'Hoefler Text',
    'Iowan Old Style',
    'Janson',
    'Joanna',
    'Junicode',
    'Korinna',
    'Liberation Serif',
    'Linux Libertine',
    'Literata',
    'Literaturnaya',
    'Lucida Bright',
    'Minion',
    'Mrs Eaves',
    'MS Serif',
    'New York',
    'Nilland',
    'Palatino',
    'Perpetua',
    'Plantin',
    'IBM Plex Serif',
    'Rawlinson Roadway',
    'Requiem',
    'Roboto Slab',
    'Rockwell',
    'Rotis',
    'Sabon',
    'Serifa',
    'Source Serif Pro',
    'Souvenir',
    'Theano Didot',
    'Times New Roman',
    'Trajan',
    'Trinité',
    'Trump Mediaeval',
    'Utopia',
    'Windsor',
    'Zilla Slab',
];

// List of sans serif typefaces 无衬线字体
const sans_serif = [
    'Agency FB',
    'Akzidenz-Grotesk',
    'Amplitude',
    'Andalé Sans',
    'Antique Olive',
    'Arial',
    'Arial Rounded',
    'Austria',
    'ITC Avant Garde Gothic',
    'Avenir',
    'Bahnschrift',
    'Bank Gothic',
    'Bell Centennial',
    'Bell Gothic',
    'Benguiat Gothic',
    'Bobcaygeon',
    'Breeze Sans',
    'Calibri',
    'Candara',
    'Cantarell',
    'Caractères',
    'Century Gothic',
    'Charcoal',
    'Chicago',
    'Adobe',
    'Clear Sans (Intel)',
    'Clearview',
    'Comic Neue',
    'Comic Sans',
    'Consolas',
    'Corbel',
    'FF Dax',
    'DejaVu Sans',
    'DIN 1451',
    'Drogowskaz',
    'Droid Sans',
    'Dubai',
    'Eras',
    'Eurostile',
    'e-Ukraine',
    'Fira Sans',
    'Folio',
    'Franklin Gothic',
    'Frutiger',
    'Futura',
    'Geneva',
    'Gerstner Programm',
    'Gill Sans',
    'Gotham',
    'Haettenschweiler',
    'Handel Gothic',
    'Helvetica',
    'Highway Gothic',
    'IBM Plex Sans',
    'Impact',
    'Interstate',
    'IBM Plex Sans',
    'Johnston',
    'Kabel',
    'Klavika',
    'Lato',
    'Liberation Sans',
    'Libre Franklin',
    'Linux Biolinum',
    'Lucida Grande',
    'Lucida Sans',
    'FS Me',
    'FF Meta',
    'Microsoft Sans Serif',
    'Montserrat',
    'Myriad',
    'National Trust',
    'News Gothic',
    'Neuzeit S',
    'Nokia Pure',
    'Noto Sans',
    'OCR-B',
    'Open Sans',
    'Optima',
    'Overpass',
    'Oxygen',
    'Proxima Nova',
    'Radis Sans',
    'Rail Alphabet',
    'Roboto',
    'San Francisco',
    'FF Scala Sans',
    'Segoe UI',
    'Selawik',
    'Semplicità',
    'Seravek',
    'Skia',
    'OnePlus',
    'SNV',
    'Source Sans Pro',
    'Sweden Sans',
    'Syntax',
    'Tahoma',
    'Thesis Sans',
    'Tiresias',
    'Trade Gothic',
    'Transport',
    'Tratex',
    'Trebuchet MS',
    'Ubuntu',
    'Unica',
    'Univers',
    'Universalis',
    'VAG Rounded',
    'Vera Sans',
    'Verdana',
    'Whitney',
];

// List of script typefaces 脚本字体
const script = [
    'American Scribe',
    'AMS Euler',
    'Apple Chancery',
    'Brush Script',
    'Cézanne',
    'Coronet',
    'Declaration Script',
    'Declare',
    'Edwardian Script',
    'FIG Script',
    'French Script',
    'Gravura',
    'Kuenstler Script',
    'Lucida Calligraphy',
    'Monotype Corsiva',
    'Snell Roundhand',
    'Zapf Chancery',
    'Zapfino',
];

// List of monospaced typefaces 等宽字体
const monospace = [
    'Cascadia Code',
    'Consolas',
    'Courier',
    'Cutive Mono',
    'DejaVu Sans Mono',
    'Droid Sans Mono',
    'Everson Mono',
    'Fira Mono',
    'Fixed',
    'Fixedsys',
    'FreeMono',
    'Go',
    'HyperFont',
    'IBM Plex Mono',
    'Inconsolata',
    'Iosevka',
    'Letter Gothic',
    'Liberation Mono',
    'Lucida Console',
    'Menlo',
    'Monaco',
    'Monofur',
    'Monospace (Unicode)',
    'Nimbus Mono L',
    'Noto Mono',
    'OCR-A',
    'OCR-B',
    'Overpass Mono',
    'Oxygen Mono',
    'PragmataPro',
    'Prestige Elite',
    'ProFont',
    'PT Mono',
    'Roboto Mono',
    'Source Code Pro',
    'Terminus',
    'Tex Gyre Cursor',
    'UM Typewriter',
];

// List of Slab serif typefaces 粗衬线字体
const slab_serif = [
    'Slab serif',
    'Alexandria',
    'American Typewriter',
    'Athens',
    'Bitstream Charter',
    'Chaparral',
    'Charis SIL',
    'Cholla Slab',
    'Clarendon',
    'Concrete Roman',
    'Courier',
    'Courier Prime',
    'Egyptienne',
    'Guardian Egyptian',
    'Joanna',
    'Legibility Group',
    'Nilland',
    'Nimbus Mono L',
    'Produkt',
    'Reverse-contrast',
    'Roboto',
    'Serifa',
    'Skeleton Antique',
    'Solus',
    'Zilla Slab',
];

type KeyValue<T> = {key: string; value: T};

export const typefaceGroups: KeyValue<string[]>[] = [
    {
        key: 'Serif',
        value: serif,
    },
    {
        key: 'Sans Serif',
        value: sans_serif,
    },
    {
        key: 'Slab Serif',
        value: slab_serif,
    },
    {
        key: 'Script',
        value: script,
    },
    {
        key: 'Monospace',
        value: monospace,
    },
];

// List of typefaces included with Microsoft Windows
export const microsoft_windows = [
    'Aharoni',
    'Aldhabi',
    'Andalus',
    'Angsana New',
    'AngsanaUPC',
    'Aparajita',
    'Arabic Typesetting',
    'Arial',
    'Bahnschrift',
    'Batang',
    'BatangChe',
    'BIZ UDGothic, BIZ UDPGothic',
    'BIZ UDMincho, BIZ UDPMincho',
    'Book Antiqua[citation need',
    'Browallia New',
    'BrowalliaUPC',
    'Calibri',
    'Calisto MT[citation need',
    'Cambria',
    'Cambria Math',
    'Candara',
    'Century Gothic[citation need',
    'Comic Sans MS',
    'Consolas',
    'Constantia',
    'Copperplate Gothic[citation need',
    'Corbel',
    'Cordia New',
    'CordiaUPC',
    'Courier New',
    'DaunPenh',
    'David',
    'DengXian',
    'DilleniaUPC',
    'DFKai-SB',
    'DokChampa',
    'Dotum',
    'DotumChe',
    'Ebrima',
    'Estrangelo Edessa',
    'EucrosiaUPC',
    'Euphemia',
    'FangSong',
    'Franklin Gothic',
    'FrankRuehl',
    'FreesiaUPC',
    'Gabriola',
    'Gadugi',
    'Gautami',
    'Georgia',
    'Gisha',
    'Gulim',
    'GulimChe',
    'Gungsuh',
    'GungsuhChe',
    'HoloLens MDL2 Assets',
    'Impact',
    'Ink Free',
    'IrisUPC',
    'Iskoola Pota',
    'JasmineUPC',
    'Javanese Text',
    'KaiTi[6] (SimK',
    'Kalinga',
    'Kartika',
    'Khmer UI',
    'KodchiangUPC',
    'Kokila',
    'Lao UI',
    'Latha',
    'Leelawadee',
    'Leelawadee UI',
    'Levenim MT',
    'LilyUPC',
    'Lucida Console',
    'Lucida Handwriting[citation need',
    'Lucida Sans Unicode',
    'Malgun Gothic',
    'Mangal',
    'Marlett',
    'Meiryo, Meiryo UI',
    'Microsoft Himalaya',
    'Microsoft JhengHei',
    'Microsoft JhengHei UI',
    'Microsoft New Tai Lue',
    'Microsoft PhagsPa',
    'Microsoft Sans Serif',
    'Microsoft Tai Le',
    'Microsoft Uighur',
    'Microsoft YaHei',
    'Microsoft YaHei UI',
    'Microsoft Yi Baiti',
    'MingLiU, PMingLiU',
    'MingLiU-ExtB, PMingLiU-ExtB',
    'MingLiU_HKSCS',
    'MingLiU_HKSCS-ExtB',
    'Miriam',
    'Miriam Fixed',
    'Mongolian Baiti',
    'MoolBoran',
    'MS Gothic',
    'MS PGothic',
    'MS Mincho',
    'MS PMincho',
    'MS UI Gothic',
    'MV Boli',
    'Myanmar Text',
    'Narkisim',
    'Nirmala UI',
    'NSimSun',
    'Nyala',
    'OCR-A Exten',
    'Palatino Linotype',
    'Plantagenet Cherokee',
    'Raavi',
    'Rod',
    'Sakkal Majalla',
    'Sanskrit Text',
    'Segoe MDL2 Assets',
    'Segoe Print',
    'Segoe Script',
    'Segoe SD[citation need',
    'Segoe UI',
    'Segoe UI Emoji',
    'Segoe UI Historic',
    'Segoe UI Symbol',
    'Segoe Fluent Ic',
    'Shonar Bangla',
    'Shruti',
    'SimHei',
    'Simplified Arabic',
    'SimSun',
    'SimSun-ExtB',
    'Sitka Banner',
    'Sitka Display',
    'Sitka Heading',
    'Sitka Small',
    'Sitka Subheading',
    'Sitka Text',
    'Sylfaen',
    'Symbol',
    'Tahoma',
    'Times New Roman',
    'Traditional Arabic',
    'Trebuchet MS',
    'Tunga',
    'UD Digi Kyokasho N-R',
    'UD Digi Kyokasho N-B',
    'UD Digi Kyokasho NK-R',
    'UD Digi Kyokasho NK-B',
    'UD Digi Kyokasho NP-R',
    'UD Digi Kyokasho NP-B',
    'Urdu Typesetting',
    'Utsaah',
    'Vani',
    'Verdana',
    'Vijaya',
    'Vrinda',
    'Webdings',
    'Wingdings',
    'Yu Gothic',
    'Yu Gothic UI',
    'Yu Mincho',
];

// List of typefaces included with macOS
export const mac_os = [
    'Al Ba',
    'American Typewri',
    'Andalé M',
    'Apple Cas',
    'Apple Chanc',
    'Apple Garam',
    'Apple Got',
    'Apple LiGot',
    'Apple LiS',
    'Apple Myun',
    'Apple Symb',
    'AquaK',
    'Ar',
    'Arial Heb',
    'Ayuth',
    'Bagh',
    'Baskervi',
    'Beij',
    'Biau',
    'Big Cas',
    'Browallia ',
    'Browallia',
    'Brush Scr',
    'Cand',
    'Chalkbo',
    'Chalkdus',
    'Charc',
    'Charcoal',
    'Chic',
    'Coc',
    'Comic S',
    'Conso',
    'Coo',
    'Copperpl',
    'Corsiva Heb',
    'Cour',
    'Courier ',
    'DecoType Na',
    'Devanag',
    'Di',
    'Euphemia U',
    'Fut',
    'Gad',
    'Geeza ',
    'Gee',
    'Gen',
    'Geneva',
    'Geor',
    'Gill S',
    'Gujar',
    'Gung Seo',
    'Gurmu',
    'Hangang',
    'Headli',
    '',
    'Helvet',
    'Helvetica',
    'Helvetica N',
    'Hercula',
    'Hiragino Kaku Gothic ',
    'Hiragino Kaku Gothic P',
    'Hiragino Kaku Gothic ',
    'Hiragino Kaku Gothic S',
    'Hiragino Maru Gothic ',
    'Hiragino Maru Gothic P',
    'Hiragino Mincho ',
    'Hiragino Mincho P',
    'Hoefler T',
    'Inai Ma',
    'Imp',
    'Jung Got',
    '',
    'Keybo',
    'Krungt',
    'KufiStandard',
    'Kuenstler Scr',
    'LastRes',
    'LiHei ',
    'LiSong ',
    'Lucida S',
    'Marker F',
    'Me',
    'Mon',
    'Monaco',
    'Mshta',
    'Nad',
    'New Peni',
    'New Y',
    'NISC GB18',
    'Opt',
    'Os',
    'Palat',
    'Papy',
    'PC Myun',
    'Pilgi',
    'Plantagenet Chero',
    'Raan',
    'S',
    'Sa',
    'Se',
    'Shin Myungjo N',
    'Si',
    'S',
    'Snell Roundh',
    'ST FangS',
    'ST FangSon',
    'ST He',
    'ST Ka',
    'ST S',
    'Sym',
    'Tae Grap',
    'Tah',
    'Tai',
    'Tec',
    'Text',
    'Thonb',
    'Ti',
    'Times',
    'Times New Ro',
    'Trebuchet',
    'Verd',
    'Zapf Chanc',
    'Zapf Dingb',
    'Zapf',
];
